/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JCheckBox;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.JButton;
/**
 *
 * @author HP
 */
public class Login extends JFrame {

    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Loginpanel = new javax.swing.JPanel();
        jCBshowpassword = new javax.swing.JCheckBox();
        jPFpassword = new javax.swing.JPasswordField();
        jpasswordfield = new javax.swing.JLabel();
        jLbusername = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        Usernametxt = new javax.swing.JTextField();
        Exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Loginpanel.setBackground(new java.awt.Color(102, 204, 255));
        Loginpanel.setForeground(new java.awt.Color(255, 0, 51));
        Loginpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCBshowpassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCBshowpassword.setText("show password");
        jCBshowpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBshowpasswordActionPerformed(evt);
            }
        });
        Loginpanel.add(jCBshowpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jPFpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPFpasswordActionPerformed(evt);
            }
        });
        Loginpanel.add(jPFpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 249, 30));

        jpasswordfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpasswordfield.setText("password");
        Loginpanel.add(jpasswordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, -1));

        jLbusername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbusername.setForeground(new java.awt.Color(0, 0, 51));
        jLbusername.setText("Username");
        Loginpanel.add(jLbusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, -1));

        Login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_pacakage/login.png"))); // NOI18N
        Login.setText("Log In");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        Loginpanel.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 110, -1));
        Loginpanel.add(Usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 42, 250, 30));

        getContentPane().add(Loginpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 310, 260));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_pacakage/Close all jframe.png"))); // NOI18N
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_pacakage/old-age-home background picture.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1970, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginFunction(){
         String username = Usernametxt.getText();
        String password = new String(jPFpassword.getPassword());
        if (username.equals("admin") && password.equals("password")) {
        JOptionPane.showMessageDialog(this, "Login Successful!");
        new HomePage().setVisible(true); //
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Invalid Username or Password!");
     }
    }
    
    private void jPFpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPFpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPFpasswordActionPerformed

    private void jCBshowpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBshowpasswordActionPerformed
{
                if (jCBshowpassword.isSelected()) {
                    jPFpassword.setEchoChar((char) 0); // Show password
                } else {
                    jPFpassword.setEchoChar('•'); // Hide password
                }        
    }//GEN-LAST:event_jCBshowpasswordActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        LoginFunction();
     
    }//GEN-LAST:event_LoginActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Login;
    private javax.swing.JPanel Loginpanel;
    private javax.swing.JTextField Usernametxt;
    private javax.swing.JCheckBox jCBshowpassword;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLbusername;
    private javax.swing.JPasswordField jPFpassword;
    private javax.swing.JLabel jpasswordfield;
    // End of variables declaration//GEN-END:variables
}

