/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author HP
 */
public class ManageRoom extends javax.swing.JFrame {

    /**
     * Creates new form ManageRoom
     */
    public ManageRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RoomIDTxt = new javax.swing.JTextField();
        Backgroundpanel = new javax.swing.JPanel();
        Addbutton = new javax.swing.JButton();
        Updatebutton = new javax.swing.JButton();
        DeleteRoom = new javax.swing.JButton();
        Clearbutton = new javax.swing.JButton();
        Availability = new javax.swing.JLabel();
        Availabilitycombobox = new javax.swing.JComboBox<>();
        Capacity = new javax.swing.JLabel();
        CapacityTxt = new javax.swing.JTextField();
        RoomType = new javax.swing.JLabel();
        RoomTxt = new javax.swing.JComboBox<>();
        RoomID = new javax.swing.JLabel();
        ManageRoom = new javax.swing.JLabel();
        Backgroundlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RoomIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomIDTxtActionPerformed(evt);
            }
        });
        getContentPane().add(RoomIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 151, 140, -1));

        Backgroundpanel.setBackground(new java.awt.Color(102, 204, 255));

        Addbutton.setBackground(new java.awt.Color(255, 102, 102));
        Addbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Addbutton.setText("Add Room");

        Updatebutton.setBackground(new java.awt.Color(255, 102, 102));
        Updatebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Updatebutton.setText("Update Room");

        DeleteRoom.setBackground(new java.awt.Color(255, 102, 102));
        DeleteRoom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteRoom.setText("Delete Room");

        Clearbutton.setBackground(new java.awt.Color(255, 102, 102));
        Clearbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Clearbutton.setText("Clear All");

        Availability.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Availability.setText("Availability");

        Availabilitycombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Capacity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Capacity.setText("Capacity");

        CapacityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacityTxtActionPerformed(evt);
            }
        });

        RoomType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RoomType.setText("Room Type");

        RoomTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        RoomTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomTxtActionPerformed(evt);
            }
        });

        RoomID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RoomID.setText("Room ID");

        ManageRoom.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ManageRoom.setText("      Manage Room");

        javax.swing.GroupLayout BackgroundpanelLayout = new javax.swing.GroupLayout(Backgroundpanel);
        Backgroundpanel.setLayout(BackgroundpanelLayout);
        BackgroundpanelLayout.setHorizontalGroup(
            BackgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundpanelLayout.createSequentialGroup()
                .addGroup(BackgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Addbutton)
                        .addGap(50, 50, 50)
                        .addComponent(Updatebutton)
                        .addGap(56, 56, 56)
                        .addComponent(DeleteRoom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Clearbutton))
                    .addGroup(BackgroundpanelLayout.createSequentialGroup()
                        .addGroup(BackgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BackgroundpanelLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(BackgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Capacity, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Availability, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RoomID, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(89, 89, 89)
                                .addGroup(BackgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RoomTxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CapacityTxt)
                                    .addComponent(Availabilitycombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(BackgroundpanelLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(ManageRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 215, Short.MAX_VALUE)))
                .addContainerGap())
        );
        BackgroundpanelLayout.setVerticalGroup(
            BackgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundpanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ManageRoom)
                .addGap(30, 30, 30)
                .addComponent(RoomID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(BackgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomType))
                .addGap(31, 31, 31)
                .addGroup(BackgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CapacityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Capacity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(BackgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Availability, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Availabilitycombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(BackgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addbutton)
                    .addComponent(Updatebutton)
                    .addComponent(DeleteRoom)
                    .addComponent(Clearbutton))
                .addGap(48, 48, 48))
        );

        getContentPane().add(Backgroundpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 610, 420));

        Backgroundlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_pacakage/old-age-home background picture.jpg"))); // NOI18N
        Backgroundlabel.setText("jLabel1");
        getContentPane().add(Backgroundlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RoomTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomTxtActionPerformed

    private void RoomIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomIDTxtActionPerformed

    private void CapacityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacityTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbutton;
    private javax.swing.JLabel Availability;
    private javax.swing.JComboBox<String> Availabilitycombobox;
    private javax.swing.JLabel Backgroundlabel;
    private javax.swing.JPanel Backgroundpanel;
    private javax.swing.JLabel Capacity;
    private javax.swing.JTextField CapacityTxt;
    private javax.swing.JButton Clearbutton;
    private javax.swing.JButton DeleteRoom;
    private javax.swing.JLabel ManageRoom;
    private javax.swing.JLabel RoomID;
    private javax.swing.JTextField RoomIDTxt;
    private javax.swing.JComboBox<String> RoomTxt;
    private javax.swing.JLabel RoomType;
    private javax.swing.JButton Updatebutton;
    // End of variables declaration//GEN-END:variables
}
